# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc6bbf1bd5044a6591a64ce42f989564fc79c1f839ca186a3c4e0112d8c42870d4940e3729a11dfcfafd1952ac81a9404fef5b1046f2daed507f2451d2a70448

test:
  secret_key_base: 24b1a87cae1457a0511322acb1b229835365d7075b2f227a5fccb4492adf23d9731bbdbf6d2e52849669d2042d8cbf935d25611699d7e5a1283e03dd41342ad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
